"""Tracking service package.

This subpackage exposes a lightweight web API to collect engagement
events generated by email recipients.  Clients include the tracking pixel
embedded in each email, click redirects, unsubscribe links and complaint
handlers.  The server implementation lives in :mod:`server` and can be
deployed standalone or embedded within the Streamlit dashboard.
"""

from __future__ import annotations

__all__: list[str] = ["server"]
