"""Web server for tracking email engagement events.

This module exposes a typed API using FastAPI.  It records events such as
opens (via a pixel), clicks, unsubscribes and complaints into a local
SQLite database.  The server can be run standalone::

    uvicorn email_marketing.tracking.server:app --reload

or embedded inside the Streamlit dashboard through :func:`create_app`.
"""

from __future__ import annotations

import base64
import datetime as dt
import os
import sqlite3
import uuid
from typing import Optional

from fastapi import FastAPI, Request, Response
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, EmailStr


def _get_db_path() -> str:
    return os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "data", "email_events.db"
    )


def _init_db() -> None:
    os.makedirs(os.path.dirname(_get_db_path()), exist_ok=True)
    with sqlite3.connect(_get_db_path()) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                msg_id TEXT NOT NULL,
                event_type TEXT NOT NULL,
                client_ip TEXT,
                ts TEXT NOT NULL
            )
            """
        )


def _record_event(msg_id: str, event_type: str, client_ip: Optional[str]) -> None:
    """Insert a new event into the SQLite database."""
    with sqlite3.connect(_get_db_path()) as conn:
        conn.execute(
            "INSERT INTO events (msg_id, event_type, client_ip, ts) VALUES (?, ?, ?, ?)",
            (msg_id, event_type, client_ip, dt.datetime.utcnow().isoformat()),
        )
        conn.commit()


app = FastAPI(title="Mailmkt Tracking API")

_init_db()


class ClickEvent(BaseModel):
    msg_id: str
    url: str


class MsgEvent(BaseModel):
    msg_id: str


class SubscribeRequest(BaseModel):
    email: EmailStr


@app.get("/pixel", response_class=Response, summary="Tracking pixel")
async def pixel(request: Request, msg_id: str) -> Response:
    """Return a 1×1 transparent GIF and record an 'open' event.

    The ``msg_id`` query parameter identifies the message.  The client IP
    address is extracted from the request.  The returned response has an
    image/gif content type.
    """
    client_ip = request.client.host if request.client else None
    _record_event(msg_id, "open", client_ip)
    # A 1×1 transparent GIF encoded in base64
    gif_base64 = "R0lGODlhAQABAPAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="
    pixel_bytes = base64.b64decode(gif_base64)
    return Response(content=pixel_bytes, media_type="image/gif")


@app.post("/click", response_class=PlainTextResponse, summary="Record a click")
async def click(event: ClickEvent, request: Request) -> str:
    """Record a click event for a link within a message."""
    client_ip = request.client.host if request.client else None
    _record_event(event.msg_id, "click", client_ip)
    return "click recorded"


@app.post("/unsubscribe", response_class=PlainTextResponse, summary="Handle unsubscribe")
async def unsubscribe(event: MsgEvent, request: Request) -> str:
    """Record an unsubscribe event and acknowledge."""
    client_ip = request.client.host if request.client else None
    _record_event(event.msg_id, "unsubscribe", client_ip)
    return "unsubscribed"


@app.post("/complaint", response_class=PlainTextResponse, summary="Handle complaints")
async def complaint(event: MsgEvent, request: Request) -> str:
    """Record a spam complaint event."""
    client_ip = request.client.host if request.client else None
    _record_event(event.msg_id, "complaint", client_ip)
    return "complaint recorded"


@app.post("/subscribe", response_class=PlainTextResponse, summary="Request double opt-in")
async def subscribe(req: SubscribeRequest) -> str:
    """Initiate a double opt‑in process.

    Generates a confirmation token and would normally send a confirmation
    email.  Here we simply return the token for demonstration purposes.
    """
    token = uuid.uuid4().hex
    return token


@app.get("/confirm/{token}", response_class=PlainTextResponse, summary="Confirm subscription")
async def confirm(token: str) -> str:
    """Confirm a subscription given a token generated by :func:`subscribe`."""
    return f"subscription confirmed: {token}"


def create_app() -> FastAPI:
    """Return the FastAPI application instance.

    Exposing this function allows the tracking server to be embedded in
    arbitrary host environments (e.g. Streamlit).  It simply returns the
    module level ``app``.
    """
    return app
