name: keep-awake
on:
  schedule:
    - cron: '0 */6 * * *'   # cada 6 horas
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          set -euxo pipefail
          # 3 pings rápidos para asegurar tráfico
          for i in 1 2 3; do
            curl -I --max-time 20 https://moassistant.streamlit.app/ || true
            sleep 10
          done
